#!/usr/bin/env bash

GAME_ID=$(uuidgen)
CURRENT_PLAYER=($(shuf -e O X))

function move {
  cat <<EOF
{
  "gameId": "${1}",
  "player": "${2}",
  "position": ${3}
}
EOF
}

function next_player {
  local current=$1
  if [ $current = O ]; then
    echo X
  else
    echo O
  fi
}

echo "Game:   ${GAME_ID}"
for p in $(shuf -e 0 1 2 3 4 5 6 7 8); do
  NEXT_MOVE=$(move ${GAME_ID} ${CURRENT_PLAYER} ${p})
  echo "Play:   (${CURRENT_PLAYER},${p}) $(curl -s -H "Content-Type:application/json" --data "${NEXT_MOVE}" http://localhost:5000/ttt/moves)"
  CURRENT_PLAYER=$(next_player ${CURRENT_PLAYER})
done

echo "Result: $(curl -s http://localhost:5000/ttt/${GAME_ID})"
