#!/usr/bin/env bash

API=http://localhost:5000/ttt

DATA="{\"id\": \"$(uuidgen)\"}"
LAST_MOVE="$(curl -H 'Content-Type:application/json' -X POST "${API}" --data "${DATA}")"
GAME_ID=$(echo "${LAST_MOVE}" | jq -r '.id')
echo ${LAST_MOVE}

function move {
  local POSITION=${1}
  local NEXT_PLAYER=$(echo "${LAST_MOVE}" | jq -r '.game.currentPlayer')
  local LOCATION="${API}/${GAME_ID}/moves"
  local DATA="{\"player\": \"${NEXT_PLAYER}\", \"position\": ${POSITION}}"
  LAST_MOVE=$(curl -s -H 'Content-Type:application/json' ${LOCATION} --data "${DATA}")
  echo "${LAST_MOVE}"
}

for p in $(shuf -e 0 1 2 3 4 5 6 7 8); do
  move "${p}"
done
