sequenceDiagram
  participant c as client
  participant q as query
  participant b as event bus
  participant s as command
  participant d as ttt domain

  q->>+b: Subscribe:<br>- MatchCreated<br>- ChallengeCreated<br>- GameCreated<br> - MoveCreated
  note left of q: listen to changes on the domain
  b--x-q: Match




  note over c,d: joining a match<br />(workflows: CreateMatch, CreateGame)

  c->>+s: Mutation(JoinMatch, Player)
    s->>d: JoinGameCommand(Player)

      activate d

      d->>d: Handle Command
        alt Workflow = CreateMatch
          d->>d: Run workflow: CreateMatch
        else Workflow = CreateGame
          d ->>d: Run workflow: CreateGame
        else Otherwise
          d ->>d: List of errors
        end
        note right of d: these state transitions <br /> DON'T create new moves
      d-->>s: Result = Match or List of errors

      deactivate d

    alt Result=Match
      s->>b: Publish(MatchCreated | GameCreated)
    end

  s-->>-c: Result = Match or List of errors




  note over c,d: playing moves <br />(workflows: CreateChallenge, PlayMove)
  c->>+q: Subscribe:<br>- MatchChanged with Match.id
  q--x-c: Match

  c->>+s: Mutation(PlayMove, MatchId, Move)
    s->>d: PlayMoveCommand(MatchId, Move)


      activate d

      d->>d: Handle Command
        alt Workflow = CreateChallenge
          d->>d: Run workflow: CreateChallenge
        else Workflow = CreateMove
          d ->>d: Run workflow: CreateMove
        else Otherwise
          d ->>d: List of errors
        end
        note right of d: these state transitions <br /> DO create new moves
      d-->>s: Result = Match or List of errors

      deactivate d

    alt Result=Match
      s->>b: Publish(ChallengeCreated | MoveCreated)
    end

  s-->>-c: Result = Match or List of errors
